### ISSUE TITLE
我用openwrt的docker运行的这个镜像，可能因为Linux内核的原因是无法直接在网页更新游戏的，只能更新容器，请问您这个仓库的dst是实时更新的吗，后续会一直维护吗

### ISSUE THREAD

**Issue by hiscatwang** [kairlec/dst-admin-go-docker#1]
我用openwrt的docker运行的这个镜像，可能因为Linux内核的原因是无法直接在网页更新游戏的，只能更新容器，请问您这个仓库的dst是实时更新的吗，后续会一直维护吗

**Comment by kairlec** [comment]
- 更新游戏的操作是调用SteamCMD来进行更新的,如果你能第一次运行起来的话应该是在网页内更新游戏的
- 如果必须更新容器,只需要注意将存档和配置等做好挂载,这个仓库每天会由Github Action自动打包一个最新的dst-admin-go与最新的游戏本体的镜像,目前会仍然保持维护

**Comment by Koolercat** [comment]
> 需要注意的是，SteamCMD 仅提供 32 位二进制文件。如果您的系统仅能运行 64 位进程（例如 OpenWRT 系统），将不能正常使用。
[https://blog.towind.fun/posts/run-dont-starve-server/](url)
